name: Download Wikipedia Article

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Wikipedia article title'
        required: true
        default: 'תל אביב'
      lang:
        description: 'Wikipedia language code'
        required: false
        default: 'he'

jobs:
  download-article:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run Wikipedia HTML download script
        run: python download_wikipedia.py "${{ github.event.inputs.title }}" "${{ github.event.inputs.lang }}"

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: article-pdf
          path: article.pdf
