name: Download Video

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'Video URL'
        required: true
        type: string
      video_type:
        description: 'Video Type (youtube/instagram)'
        required: true
        default: 'youtube'
        type: string

jobs:
  download-and-save:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install yt-dlp

      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Download cookies.txt from repository (if exists)
        run: |
          if [ -f cookies.txt ]; then
            echo "cookies.txt found"
          else
            echo "No cookies.txt found"
          fi

      - name: Download and save video
        run: |
          if [ "${{ github.event.inputs.video_type }}" = "youtube" ]; then
            python download_and_zip1.py "${{ github.event.inputs.video_url }}"
          elif [ "${{ github.event.inputs.video_type }}" = "instagram" ] || [ "${{ github.event.inputs.video_type }}" = "tiktok" ]; then
            TITLE=$(yt-dlp --get-title "${{ github.event.inputs.video_url }}" | head -n 1)
            SAFE_TITLE=$(echo "$TITLE" | tr -cd '[:alnum:] ._-')
            yt-dlp --ffmpeg-location /usr/bin/ffmpeg -o "${SAFE_TITLE}.%(ext)s" "${{ github.event.inputs.video_url }}"
            zip "${SAFE_TITLE}.zip" "${SAFE_TITLE}."*
          else
            echo "Unknown video type: ${{ github.event.inputs.video_type }}"
            exit 1
          fi

      - name: Upload video artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.video_type }}-video
          path: |
            *.zip
            *.mp4
