name: Generate Image from Text Prompt

on:
  workflow_dispatch:

jobs:
  generate-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
          pip install diffusers transformers accelerate safetensors

      - name: Run image generation script
        run: python generate_image.py

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: generated-image
          path: output.png
