name: Generate GIF from Text Prompt

on:
  workflow_dispatch:

jobs:
  generate-gif:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
          pip install diffusers transformers accelerate imageio

      - name: Run GIF generation script
        run: python generate_gif.py

      - name: Upload GIF artifact
        uses: actions/upload-artifact@v4
        with:
          name: generated-gif
          path: output.gif
