name: Google Search

on:
  workflow_dispatch:
    inputs:
      query:
        description: 'Search query'
        required: true
        default: 'python'

jobs:
  search:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install requests beautifulsoup4
      - name: Run Google Search
        run: python google_search.py "${{ github.event.inputs.query }}"
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: google-results
          path: results.json
